name: Test on Multiple OS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18, 20, 22]
        attempt: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Upgrade node-gyp (Linux/macOS only)
        if: matrix.os != 'windows-latest'
        run: |
          npm install -g node-gyp@latest
          echo "Upgraded node-gyp to $(node-gyp --version)"

      - name: Use Python 2 for node-gyp (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python2
          npm config set python /usr/bin/python2

      - name: Install dependencies
        run: npm install --force

      - name: Testing on OS (${{ matrix.os }}) with Node.js (version ${{ matrix.node-version }}) attempt ${{ matrix.attempt }}
        run: |
          echo "Run attempt: ${{ matrix.attempt }}"
          npm test

    continue-on-error: false
